// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoVUc9hD7HrUW9PrZepLTyG0mdvqTZHUk',
    appId: '1:868804393175:web:220d4fe16897b370b7d892',
    messagingSenderId: '868804393175',
    projectId: 'seller-app-syria',
    authDomain: 'seller-app-syria.firebaseapp.com',
    storageBucket: 'seller-app-syria.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzlY3d_6HkyTfco1j9VU7XHSB38EyyB4s',
    appId: '1:868804393175:ios:a0f7a5991a70216eb7d892',
    messagingSenderId: '868804393175',
    projectId: 'seller-app-syria',
    storageBucket: 'seller-app-syria.firebasestorage.app',
    iosBundleId: 'com.example.merchantDashboard',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzlY3d_6HkyTfco1j9VU7XHSB38EyyB4s',
    appId: '1:868804393175:ios:a0f7a5991a70216eb7d892',
    messagingSenderId: '868804393175',
    projectId: 'seller-app-syria',
    storageBucket: 'seller-app-syria.firebasestorage.app',
    iosBundleId: 'com.example.merchantDashboard',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhTaUu3P5PbFnCyCLM__T9leg-l47j_9I',
    appId: '1:868804393175:android:2c3330f9435d7933b7d892',
    messagingSenderId: '868804393175',
    projectId: 'seller-app-syria',
    storageBucket: 'seller-app-syria.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoVUc9hD7HrUW9PrZepLTyG0mdvqTZHUk',
    appId: '1:868804393175:web:ab2a88a55a5a30a3b7d892',
    messagingSenderId: '868804393175',
    projectId: 'seller-app-syria',
    authDomain: 'seller-app-syria.firebaseapp.com',
    storageBucket: 'seller-app-syria.firebasestorage.app',
  );

}